"""Generator script for test_skill_gap.py"""
from pathlib import Path

lines = []
def w(s=""):
    lines.append(s)

w('"""Tests for Skill Gap Analysis and Learning Roadmap."""')
w('import pytest')
w('from app.models.career import Career')
w('from app.models.career_job_mapping import CareerJobMapping, MappingType')
w('from app.models.job import Job')
w('from app.models.job_skill import JobSkill')
w('from app.models.skill import Skill, SkillCategory')
w('from app.models.student import StudentProfile')
w('from app.models.student_skill import StudentSkill')
w('from app.models.user import User, UserRole')
w('from app.core.security import hash_password')
w('from app.services.skill_gap_service import (')
w('    classify_priority, compute_priority_scores, compute_skill_gap,')
w('    get_career_required_skills, get_job_required_skills, get_student_skill_ids,')
w(')')
w('from app.services.learning_roadmap_service import generate_roadmap_from_gap')
w()
w()
w('def _make_skill(db, name):')
w('    skill = Skill(name=name, normalized_name=name.lower().replace(" ", "_").replace("-", "_"), category=SkillCategory.technical)')
w('    db.add(skill)')
w('    db.flush()')
w('    return skill')
w()
w('def _make_student_skill(db, student_id, skill_id, proficiency=7):')
w('    ss = StudentSkill(student_id=student_id, skill_id=skill_id, proficiency=proficiency)')
w('    db.add(ss)')
w('    db.flush()')
w('    return ss')
w()
w('def _make_career(db, name):')
w('    career = Career(name=name, normalized_name=name.lower().replace(" ", "_"))')
w('    db.add(career)')
w('    db.flush()')
w('    return career')
w()
w('def _make_job(db, title, company="ACME", city="Karachi"):')
w('    job = Job(job_title=title, job_title_clean=title.lower(), company=company, city=city, sector="IT")')
w('    db.add(job)')
w('    db.flush()')
w('    return job')
w()
w('def _make_job_skill(db, job_id, skill_id, importance=5):')
w('    js = JobSkill(job_id=job_id, skill_id=skill_id, importance=importance)')
w('    db.add(js)')
w('    db.flush()')
w('    return js')
w()
w('def _make_mapping(db, career_id, job_title_clean):')
w('    m = CareerJobMapping(career_id=career_id, job_title_clean=job_title_clean, mapping_type=MappingType.strong, confidence="0.8")')
w('    db.add(m)')
w('    db.flush()')
w('    return m')
w()
w()
w('@pytest.fixture')
w('def auth_client(client, db_session):')
w('    """Register a user and return (client, auth_headers, profile)."""')
w('    response = client.post("/api/auth/register", json={')
w('        "email": "gap_test@example.com",')
w('        "password": "Password123!",')
w('        "confirm_password": "Password123!",')
w('        "full_name": "Gap Student",')
w('    })')
w('    assert response.status_code == 201')
w('    token = response.json()["access_token"]')
w('    headers = {"Authorization": f"Bearer {token}"}')
w('    profile = db_session.query(StudentProfile).join(User).filter(User.email == "gap_test@example.com").first()')
w('    return client, headers, profile')
w()
w()
w('class TestSkillGapService:')
w('    def test_get_student_skill_ids(self, db_session):')
w('        from app.models.user import User, UserRole')
w('        user = User(email="svc1@test.com", password_hash="h", role=UserRole.student)')
w('        db_session.add(user)')
w('        db_session.flush()')
w('        profile = StudentProfile(user_id=user.id, full_name="S", age=22, gender="M", university_year="Senior", major="CS", cgpa=3.5, attendance_percentage=88, study_hours_per_week=18, projects_completed=4, certifications_count=1, internships=1, communication_skills=7, teamwork=7, problem_solving=8, interest_domain="Software Development")')
w('        db_session.add(profile)')
w('        db_session.flush()')
w('        s1 = _make_skill(db_session, "Python")')
w('        s2 = _make_skill(db_session, "SQL")')
w('        _make_student_skill(db_session, profile.id, s1.id)')
w('        _make_student_skill(db_session, profile.id, s2.id, proficiency=4)')
w('        db_session.commit()')
w('        ids = get_student_skill_ids(db_session, profile.id)')
w('        assert ids == {s1.id, s2.id}')
w()
w('    def test_get_student_skill_ids_empty(self, db_session):')
w('        from app.models.user import User, UserRole')
w('        user = User(email="svc2@test.com", password_hash="h", role=UserRole.student)')
w('        db_session.add(user)')
w('        db_session.flush()')
w('        profile = StudentProfile(user_id=user.id, full_name="S", age=22, gender="M", university_year="Senior", major="CS", cgpa=3.5, attendance_percentage=88, study_hours_per_week=18, projects_completed=4, certifications_count=1, internships=1, communication_skills=7, teamwork=7, problem_solving=8, interest_domain="Software Development")')
w('        db_session.add(profile)')
w('        db_session.flush()')
w('        db_session.commit()')
w('        ids = get_student_skill_ids(db_session, profile.id)')
w('        assert ids == set()')
w()
w('    def test_compute_skill_gap(self, db_session):')
w('        from app.models.user import User, UserRole')
w('        user = User(email="svc3@test.com", password_hash="h", role=UserRole.student)')
w('        db_session.add(user)')
w('        db_session.flush()')
w('        profile = StudentProfile(user_id=user.id, full_name="S", age=22, gender="M", university_year="Senior", major="CS", cgpa=3.5, attendance_percentage=88, study_hours_per_week=18, projects_completed=4, certifications_count=1, internships=1, communication_skills=7, teamwork=7, problem_solving=8, interest_domain="Software Development")')
w('        db_session.add(profile)')
w('        db_session.flush()')
w('        s1 = _make_skill(db_session, "Python")')
w('        s2 = _make_skill(db_session, "SQL")')
w('        s3 = _make_skill(db_session, "Docker")')
w('        _make_student_skill(db_session, profile.id, s1.id)')
w('        _make_student_skill(db_session, profile.id, s2.id)')
w('        db_session.commit()')
w('        required = {')
w('            s1.id: {"skill_id": s1.id, "skill_name": "Python", "normalized_name": "python", "category": "technical", "avg_importance": 8.0, "demand_count": 5},')
w('            s2.id: {"skill_id": s2.id, "skill_name": "SQL", "normalized_name": "sql", "category": "technical", "avg_importance": 7.0, "demand_count": 4},')
w('            s3.id: {"skill_id": s3.id, "skill_name": "Docker", "normalized_name": "docker", "category": "technical", "avg_importance": 6.0, "demand_count": 3},')
w('        }')
w('        result = compute_skill_gap(db_session, profile.id, required)')
w('        assert result.matched_count == 2')
w('        assert result.missing_count == 1')
w('        assert result.total_required == 3')
w('        assert result.match_percentage == 66.7')
w('        assert len(result.matched_skills) == 2')
w('        assert len(result.missing_skills) == 1')
w('        assert result.missing_skills[0].skill_name == "Docker"')
w()
w('    def test_compute_skill_gap_empty_required(self, db_session):')
w('        from app.models.user import User, UserRole')
w('        user = User(email="svc4@test.com", password_hash="h", role=UserRole.student)')
w('        db_session.add(user)')
w('        db_session.flush()')
w('        profile = StudentProfile(user_id=user.id, full_name="S", age=22, gender="M", university_year="Senior", major="CS", cgpa=3.5, attendance_percentage=88, study_hours_per_week=18, projects_completed=4, certifications_count=1, internships=1, communication_skills=7, teamwork=7, problem_solving=8, interest_domain="Software Development")')
w('        db_session.add(profile)')
w('        db_session.flush()')
w('        db_session.commit()')
w('        result = compute_skill_gap(db_session, profile.id, {})')
w('        assert result.match_percentage == 0.0')
w('        assert result.total_required == 0')
w()
w('    def test_compute_skill_gap_all_matched(self, db_session):')
w('        from app.models.user import User, UserRole')
w('        user = User(email="svc5@test.com", password_hash="h", role=UserRole.student)')
w('        db_session.add(user)')
w('        db_session.flush()')
w('        profile = StudentProfile(user_id=user.id, full_name="S", age=22, gender="M", university_year="Senior", major="CS", cgpa=3.5, attendance_percentage=88, study_hours_per_week=18, projects_completed=4, certifications_count=1, internships=1, communication_skills=7, teamwork=7, problem_solving=8, interest_domain="Software Development")')
w('        db_session.add(profile)')
w('        db_session.flush()')
w('        s1 = _make_skill(db_session, "Python")')
w('        _make_student_skill(db_session, profile.id, s1.id)')
w('        db_session.commit()')
w('        required = {s1.id: {"skill_id": s1.id, "skill_name": "Python", "normalized_name": "python", "category": "technical", "avg_importance": 5.0, "demand_count": 1}}')
w('        result = compute_skill_gap(db_session, profile.id, required)')
w('        assert result.match_percentage == 100.0')
w('        assert result.missing_count == 0')
w()
w('    def test_classify_priority(self):')
w('        assert classify_priority(80.0) == "High"')
w('        assert classify_priority(70.0) == "High"')
w('        assert classify_priority(69.9) == "Medium"')
w('        assert classify_priority(40.0) == "Medium"')
w('        assert classify_priority(39.9) == "Low"')
w('        assert classify_priority(0.0) == "Low"')
w()
w('    def test_compute_priority_scores(self):')
w('        missing = {')
w('            1: {"skill_name": "Docker", "normalized_name": "docker", "category": "technical", "avg_importance": 8.0},')
w('            2: {"skill_name": "AWS", "normalized_name": "aws", "category": "technical", "avg_importance": 5.0},')
w('        }')
w('        demand = {1: 10, 2: 3}')
w('        results = compute_priority_scores(missing, demand)')
w('        assert len(results) == 2')
w('        assert results[0].skill_name == "Docker"')
w('        assert results[0].demand_count == 10')
w('        assert results[0].priority_score > results[1].priority_score')
w()
w('    def test_compute_priority_scores_empty(self):')
w('        assert compute_priority_scores({}, {}) == []')
w()
w('    def test_get_job_required_skills(self, db_session):')
w('        job = _make_job(db_session, "Backend Developer")')
w('        s1 = _make_skill(db_session, "Python")')
w('        s2 = _make_skill(db_session, "SQL")')
w('        _make_job_skill(db_session, job.id, s1.id, importance=9)')
w('        _make_job_skill(db_session, job.id, s2.id, importance=7)')
w('        db_session.commit()')
w('        skills = get_job_required_skills(db_session, job.id)')
w('        assert len(skills) == 2')
w('        assert s1.id in skills')
w('        assert skills[s1.id]["avg_importance"] == 9.0')
w()
w('    def test_get_career_required_skills(self, db_session):')
w('        career = _make_career(db_session, "Data Analyst")')
w('        job = _make_job(db_session, "Data Analyst", company="ACME")')
w('        s1 = _make_skill(db_session, "SQL")')
w('        s2 = _make_skill(db_session, "Python")')
w('        _make_job_skill(db_session, job.id, s1.id, importance=8)')
w('        _make_job_skill(db_session, job.id, s2.id, importance=6)')
w('        _make_mapping(db_session, career.id, "data analyst")')
w('        db_session.commit()')
w('        skills = get_career_required_skills(db_session, career.id)')
w('        assert len(skills) == 2')
w('        assert s1.id in skills')
w()
w()
w('class TestSkillGapAPI:')
w('    def test_career_skill_gap(self, auth_client, db_session):')
w('        client, headers, profile = auth_client')
w('        career = _make_career(db_session, "Data Analyst")')
w('        job = _make_job(db_session, "Data Analyst")')
w('        s1 = _make_skill(db_session, "SQL")')
w('        s2 = _make_skill(db_session, "Python")')
w('        _make_student_skill(db_session, profile.id, s1.id)')
w('        _make_job_skill(db_session, job.id, s1.id, importance=8)')
w('        _make_job_skill(db_session, job.id, s2.id, importance=6)')
w('        _make_mapping(db_session, career.id, "data analyst")')
w('        db_session.commit()')
w('        response = client.get(f"/api/skill-gaps/career/{career.id}", headers=headers)')
w('        assert response.status_code == 200')
w('        data = response.json()')
w('        assert data["career"]["name"] == "Data Analyst"')
w('        assert data["skill_gap"]["matched_count"] == 1')
w('        assert data["skill_gap"]["missing_count"] == 1')
w()
w('    def test_job_skill_gap(self, auth_client, db_session):')
w('        client, headers, profile = auth_client')
w('        job = _make_job(db_session, "Backend Developer")')
w('        s1 = _make_skill(db_session, "Python")')
w('        s2 = _make_skill(db_session, "Docker")')
w('        _make_student_skill(db_session, profile.id, s1.id)')
w('        _make_job_skill(db_session, job.id, s1.id, importance=9)')
w('        _make_job_skill(db_session, job.id, s2.id, importance=7)')
w('        db_session.commit()')
w('        response = client.get(f"/api/skill-gaps/job/{job.id}", headers=headers)')
w('        assert response.status_code == 200')
w('        data = response.json()')
w('        assert data["job"]["title"] == "Backend Developer"')
w('        assert data["skill_gap"]["matched_count"] == 1')
w('        assert data["skill_gap"]["missing_count"] == 1')
w()
w('    def test_career_skill_gap_unauthorized(self, client):')
w('        response = client.get("/api/skill-gaps/career/1")')
w('        assert response.status_code in (401, 403)')
w()
w('    def test_career_skill_gap_not_found(self, auth_client):')
w('        client, headers, profile = auth_client')
w('        response = client.get("/api/skill-gaps/career/9999", headers=headers)')
w('        assert response.status_code == 404')
w()
w('    def test_job_skill_gap_not_found(self, auth_client):')
w('        client, headers, profile = auth_client')
w('        response = client.get("/api/skill-gaps/job/9999", headers=headers)')
w('        assert response.status_code == 404')
w()
w()
w('class TestLearningRoadmap:')
w('    def test_generate_roadmap_from_gap(self):')
w('        from app.services.skill_gap_service import SkillGapResult, SkillGapItemResult')
w('        gap = SkillGapResult(')
w('            matched_skills=[{"id": 1, "name": "Python"}],')
w('            missing_skills=[')
w('                SkillGapItemResult(skill_id=2, skill_name="Docker", normalized_name="docker", category="technical", priority_score=85.0, priority="High", demand_count=10, career_relevance_count=10, avg_importance=8.0),')
w('                SkillGapItemResult(skill_id=3, skill_name="AWS", normalized_name="aws", category="technical", priority_score=60.0, priority="Medium", demand_count=5, career_relevance_count=5, avg_importance=6.0),')
w('            ],')
w('            match_percentage=33.3, total_required=3, matched_count=1, missing_count=2,')
w('        )')
w('        roadmap = generate_roadmap_from_gap(gap, "Data Analyst")')
w('        assert roadmap.total_missing == 2')
w('        assert roadmap.career_name == "Data Analyst"')
w('        assert len(roadmap.roadmap) == 2')
w()
w('    def test_generate_roadmap_empty_gap(self):')
w('        from app.services.skill_gap_service import SkillGapResult')
w('        gap = SkillGapResult(matched_skills=[], missing_skills=[], match_percentage=100.0, total_required=0, matched_count=0, missing_count=0)')
w('        roadmap = generate_roadmap_from_gap(gap, "Data Analyst")')
w('        assert roadmap.total_missing == 0')
w('        assert len(roadmap.roadmap) == 0')
w()
w('    def test_roadmap_ordering(self):')
w('        from app.services.skill_gap_service import SkillGapResult, SkillGapItemResult')
w('        gap = SkillGapResult(')
w('            matched_skills=[],')
w('            missing_skills=[')
w('                SkillGapItemResult(skill_id=1, skill_name="Low Skill", normalized_name="low_skill", category="technical", priority_score=20.0, priority="Low", demand_count=1, career_relevance_count=1, avg_importance=3.0),')
w('                SkillGapItemResult(skill_id=2, skill_name="High Skill", normalized_name="high_skill", category="technical", priority_score=90.0, priority="High", demand_count=10, career_relevance_count=10, avg_importance=9.0),')
w('                SkillGapItemResult(skill_id=3, skill_name="Med Skill", normalized_name="med_skill", category="technical", priority_score=50.0, priority="Medium", demand_count=5, career_relevance_count=5, avg_importance=5.0),')
w('            ],')
w('            match_percentage=0.0, total_required=3, matched_count=0, missing_count=3,')
w('        )')
w('        roadmap = generate_roadmap_from_gap(gap)')
w('        assert roadmap.roadmap[0].skill == "High Skill"')
w('        assert roadmap.roadmap[1].skill == "Med Skill"')
w('        assert roadmap.roadmap[2].skill == "Low Skill"')
w()
w()
w('class TestLearningRoadmapAPI:')
w('    def test_default_roadmap_no_recommendations(self, auth_client):')
w('        client, headers, profile = auth_client')
w('        response = client.get("/api/learning-roadmap", headers=headers)')
w('        assert response.status_code == 200')
w('        data = response.json()')
w('        assert "message" in data')
w()
w('    def test_career_roadmap(self, auth_client, db_session):')
w('        client, headers, profile = auth_client')
w('        career = _make_career(db_session, "Data Analyst")')
w('        job = _make_job(db_session, "Data Analyst")')
w('        s1 = _make_skill(db_session, "SQL")')
w('        s2 = _make_skill(db_session, "Python")')
w('        _make_student_skill(db_session, profile.id, s1.id)')
w('        _make_job_skill(db_session, job.id, s1.id, importance=8)')
w('        _make_job_skill(db_session, job.id, s2.id, importance=6)')
w('        _make_mapping(db_session, career.id, "data analyst")')
w('        db_session.commit()')
w('        response = client.get(f"/api/learning-roadmap/career/{career.id}", headers=headers)')
w('        assert response.status_code == 200')
w('        data = response.json()')
w('        assert data["career_name"] == "Data Analyst"')
w('        assert data["total_missing"] >= 0')
w()
w('    def test_job_roadmap(self, auth_client, db_session):')
w('        client, headers, profile = auth_client')
w('        job = _make_job(db_session, "Backend Developer")')
w('        s1 = _make_skill(db_session, "Python")')
w('        s2 = _make_skill(db_session, "Docker")')
w('        _make_student_skill(db_session, profile.id, s1.id)')
w('        _make_job_skill(db_session, job.id, s1.id, importance=9)')
w('        _make_job_skill(db_session, job.id, s2.id, importance=7)')
w('        db_session.commit()')
w('        response = client.get(f"/api/learning-roadmap/job/{job.id}", headers=headers)')
w('        assert response.status_code == 200')
w('        data = response.json()')
w('        assert data["total_missing"] >= 0')
w()
w('    def test_roadmap_unauthorized(self, client):')
w('        response = client.get("/api/learning-roadmap")')
w('        assert response.status_code in (401, 403)')

content = "\n".join(lines) + "\n"
target = Path(__file__).parent / "test_skill_gap.py"
target.write_text(content, encoding="utf-8")
print(f"Written {target} ({len(content)} bytes, {len(lines)} lines)")
